package com.mycompany.musicchart.view;

import com.mycompany.musicchart.model.Genie;
import com.mycompany.musicchart.model.Melon;
import javax.swing.JTable;
import javax.swing.table.*;

public class MainMenu extends javax.swing.JFrame {
    Genie rg = new Genie();
    Melon rm = new Melon();
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        melonBtn = new javax.swing.JButton();
        genieBtn = new javax.swing.JButton();
        SearchMelon = new javax.swing.JButton();
        SearchGenie = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        singerTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "순위", "제목", "가수"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLabel2.setText("제목");

        titleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTextFieldActionPerformed(evt);
            }
        });

        melonBtn.setText("Melon");
        melonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                melonBtnActionPerformed(evt);
            }
        });

        genieBtn.setText("Genie");
        genieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genieBtnActionPerformed(evt);
            }
        });

        SearchMelon.setText("Search Melon");
        SearchMelon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMelonActionPerformed(evt);
            }
        });

        SearchGenie.setText("Search Genie");
        SearchGenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchGenieActionPerformed(evt);
            }
        });

        jLabel1.setText("가수");

        singerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singerTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(singerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(melonBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(genieBtn)))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchMelon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchGenie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(SearchMelon))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(melonBtn)
                                .addComponent(singerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchGenie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genieBtn))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void melonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_melonBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm;
        JTable table;
        Object[][] rowData = new Object[50][3];
        
        for(int i = 0; i < 50; i++) {
            for(int j = 0; j < 3; j++) {
                if(j == 0) {
                    rowData[i][j] = i + 1;
                }
                else if(j == 1) {
                    rowData[i][j] = rm.getListTitle().get(i);
                }
                else {
                    rowData[i][j] = rm.getListName().get(i);
                }
            }
        }
        String[] columTitle = {"순위" , "노래", "가수" };
        dtm = new DefaultTableModel(rowData, columTitle);
        
        table = new JTable(dtm);
        
        jTable1.setModel(dtm);
    }//GEN-LAST:event_melonBtnActionPerformed

    private void genieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genieBtnActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dtm;
        JTable table;
        Object[][] rowData = new Object[50][3];
        for(int i = 0; i < 50; i++) {
            for(int j = 0; j < 3; j++) {
                if(j == 0) {
                    rowData[i][j] = i + 1;
                }
                else if(j == 1) {
                    rowData[i][j] = rg.getListTitle().get(i);
                }
                else {
                    rowData[i][j] = rg.getListName().get(i);
                }
            }
        }
        String[] columTitle = {"순위" , "노래", "가수" };
        dtm = new DefaultTableModel(rowData, columTitle);
        
        table = new JTable(dtm);
        
        jTable1.setModel(dtm);
    }//GEN-LAST:event_genieBtnActionPerformed

    private void titleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextFieldActionPerformed
        
    }//GEN-LAST:event_titleTextFieldActionPerformed

    private void SearchMelonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMelonActionPerformed
        String str1 = titleTextField.getText();
        String str2 = singerTextField.getText();
        DefaultTableModel dtm;
        JTable table;
        Object[][] rowData = new Object[50][3];
        int j = 0;
        
        if(str1.isEmpty() == false){
            if(str2.isEmpty() == false) {
                for(int i=0;i<rowData.length;i++){
                    if(rm.getListTitle().get(i).contains(str1)){
                       rowData[j][0] = i+1;
                       rowData[j][1] = rm.getListTitle().get(i);
                       rowData[j][2] = rm.getListName().get(i);
                       j++;
                    }   
                }
            }
            else {
                for(int i=0;i<rowData.length;i++){
                    if(rm.getListTitle().get(i).contains(str1)){
                       rowData[j][0] = i+1;
                       rowData[j][1] = rm.getListTitle().get(i);
                       rowData[j][2] = rm.getListName().get(i);
                       j++;
                    }   
                }
            }
        } 
        else if(str2.isEmpty()==false){
            if(str1.isEmpty()) {
                for(int i=0;i<50;i++){
                    if(rm.getListName().get(i).contains(str2)){
                       rowData[j][0] = i+1;
                       rowData[j][1] = rm.getListTitle().get(i);
                       rowData[j][2] = rm.getListName().get(i);
                       j++;
                    }   
                }
            }
        }
        
        String[] columTitle = {"순위","제목","가수"};
        dtm = new DefaultTableModel(rowData,columTitle);
        
        table = new JTable(dtm);
        
        jTable1.setModel(dtm);
    }//GEN-LAST:event_SearchMelonActionPerformed

    private void SearchGenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchGenieActionPerformed
        String str1 = titleTextField.getText();
        String str2 = singerTextField.getText();
        
        DefaultTableModel dtm;
        JTable table;
        Object[][] rowData = new Object[50][3];
        int j = 0;
        
        // 이 부분 바꾸기
        System.out.println("str1  =  " + str1.isEmpty());
        if(str1.isEmpty() == false){
            if(str2.isEmpty() == false) {
                for(int i=0;i<rowData.length;i++){
                    if(rg.getListTitle().get(i).contains(str1)){
                       rowData[j][0] = i+1;
                       rowData[j][1] = rg.getListTitle().get(i);
                       rowData[j][2] = rg.getListName().get(i);
                       j++;
                    }   
                }
            }
            else {
                for(int i=0;i<rowData.length;i++){
                    if(rg.getListTitle().get(i).contains(str1)){
                       rowData[j][0] = i+1;
                       rowData[j][1] = rg.getListTitle().get(i);
                       rowData[j][2] = rg.getListName().get(i);
                       j++;
                    }   
                }
            }
        } 
        else if(str2.isEmpty()==false){
            if(str1.isEmpty()) {
                for(int i=0;i<50;i++){
                    if(rg.getListName().get(i).contains(str2)){
                       rowData[j][0] = i+1;
                       rowData[j][1] = rg.getListTitle().get(i);
                       rowData[j][2] = rg.getListName().get(i);
                       j++;
                    }   
                }
            }
        }
       
        
        String[] columTitle = {"순위","제목","가수"};
        dtm = new DefaultTableModel(rowData,columTitle);
        
        table = new JTable(dtm);
        
        jTable1.setModel(dtm);
    }//GEN-LAST:event_SearchGenieActionPerformed

    private void singerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_singerTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public void runMusicChart() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchGenie;
    private javax.swing.JButton SearchMelon;
    private javax.swing.JButton genieBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton melonBtn;
    private javax.swing.JTextField singerTextField;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
